In [87]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 01:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 01:\n")

import tensorflow as tf

# Create a 3D tensor with random float values
random_tensor = tf.random.uniform(shape=(3, 3, 3), minval=0, maxval=1, dtype=tf.float32)

# Calculate the sum, mean, and maximum of the tensor
tensor_sum = tf.reduce_sum(random_tensor)
tensor_mean = tf.reduce_mean(random_tensor)
tensor_max = tf.reduce_max(random_tensor)

# Print the results
print("Random Tensor:\n", random_tensor.numpy())
print("\n(*): Sum:", tensor_sum.numpy())
print("(*): Mean:", tensor_mean.numpy())
print("(*): Max:", tensor_max.numpy())

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 01:

Random Tensor:
 [[[0.49175453 0.2235831  0.04950428]
  [0.48287165 0.66728425 0.20076346]
  [0.2218349  0.9796109  0.06145716]]

 [[0.07868004 0.26984024 0.33341265]
  [0.89354396 0.5530654  0.4443537 ]
  [0.09298718 0.80174196 0.44810355]]

 [[0.82459366 0.10140669 0.41417754]
  [0.3959098  0.80535614 0.51828086]
  [0.5389807  0.29585636 0.56267905]]]

(*): Sum: 11.751634
(*): Mean: 0.4352457
(*): Max: 0.9796109


In [89]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 02:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 02:\n")
# Create another 3D tensor for slicing
tensor_3d = tf.constant([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])
# Access a specific element (e.g., element at position [1, 2, 1])
specific_element = tensor_3d[1, 2, 1]
# Access a 2D slice (e.g., slice of the first layer)
two_d_slice = tensor_3d[0, :, :]
# Access a 1D slice (e.g., first row of the second layer)
one_d_slice = tensor_3d[2, 1, :]
# Print the accessed elements and slices
print("TENSOR:\n", tensor_3d.numpy())
print("\n(*): Specific Element [1, 2, 1]:", specific_element.numpy())
print("(*): 2D Slice (First Layer):\n", two_d_slice.numpy())
print("(*): 1D Slice (First Row of Second Layer):", one_d_slice.numpy())

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 01 / PART 02:

TENSOR:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

(*): Specific Element [1, 2, 1]: 17
(*): 2D Slice (First Layer):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
(*): 1D Slice (First Row of Second Layer): [22 23 24]


In [91]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 02:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 02:\n")
import tensorflow as tf
# Define the tensor operations function
@tf.function
def tensor_operations(tensor1, tensor2):
    addition = tf.add(tensor1, tensor2)
    subtraction = tf.subtract(tensor1, tensor2)
    multiplication = tf.multiply(tensor1, tensor2)
    division = tf.divide(tensor1, tensor2)
    return {
        "addition": addition,
        "subtraction": subtraction,
        "multiplication": multiplication,
        "division": division
    }
# Test the function with the provided tensors
tensor1 = tf.constant([10, 20, 30], dtype=tf.float32)
tensor2 = tf.constant([5, 10, 15], dtype=tf.float32)
print("TENSOR-1:", tensor1.numpy())
print("TENSOR-2:", tensor2.numpy())
# Call the tensor_operations function
results = tensor_operations(tensor1, tensor2)
# Print the results
print("\n(*): Results of Tensor Operations:")
for operation, result in results.items():
    print(f"{operation.capitalize()}: {result.numpy()}")

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 02:

TENSOR-1: [10. 20. 30.]
TENSOR-2: [ 5. 10. 15.]

(*): Results of Tensor Operations:
Addition: [15. 30. 45.]
Subtraction: [ 5. 10. 15.]
Multiplication: [ 50. 200. 450.]
Division: [2. 2. 2.]


In [93]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 01:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 01:\n")
import numpy as np
# Create a NumPy array with random float values
random_array = np.random.rand(10)  # Array of 10 random floats
# Sort the array in ascending order
sorted_ascending = np.sort(random_array)
# Sort the array in descending order
sorted_descending = sorted_ascending[::-1]  # Reverse the sorted array
# Print the results
print("Random Array:", random_array)
print("\n(*): Sorted Ascending:", sorted_ascending)
print("\n(*): Sorted Descending:", sorted_descending)

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 01:

Random Array: [0.65181291 0.70658413 0.07058608 0.97818902 0.0973632  0.99031098
 0.88994738 0.63800224 0.83609015 0.12001561]

(*): Sorted Ascending: [0.07058608 0.0973632  0.12001561 0.63800224 0.65181291 0.70658413
 0.83609015 0.88994738 0.97818902 0.99031098]

(*): Sorted Descending: [0.99031098 0.97818902 0.88994738 0.83609015 0.70658413 0.65181291
 0.63800224 0.12001561 0.0973632  0.07058608]


In [97]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 02:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 02:\n")
# Create a 2x2 NumPy matrix
matrix_2x2 = np.array([[1, 9], [7, 4]])
# Calculate its transpose
matrix_transpose = np.transpose(matrix_2x2)
# Calculate its inverse
matrix_inverse = np.linalg.inv(matrix_2x2)
# Print the results
print("2x2 Matrix:\n", matrix_2x2)
print("\n(*): Transpose of Matrix:\n", matrix_transpose)
print("\n(*): Inverse of Matrix:\n", matrix_inverse)

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 02:

2x2 Matrix:
 [[1 9]
 [7 4]]

(*): Transpose of Matrix:
 [[1 7]
 [9 4]]

(*): Inverse of Matrix:
 [[-0.06779661  0.15254237]
 [ 0.11864407 -0.01694915]]


In [99]:
#ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 03:
print("ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 03:\n")
# Create a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Calculate the sum of each row
row_sums = np.sum(array_2d, axis=1)
# Calculate the mean of each column
column_means = np.mean(array_2d, axis=0)
# Calculate the standard deviation of the entire array
std_deviation = np.std(array_2d)
# Print the results
print("2D Array:\n", array_2d)
print("\n(*): Sum of Each Row:", row_sums)
print("(*): Mean of Each Column:", column_means)
print("(*): Standard Deviation of the Entire Array:", std_deviation)

ABDUL RAFAY / 2022F-BSE-197 / LAB 01 / TASK 03 / PART 03:

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

(*): Sum of Each Row: [ 6 15 24]
(*): Mean of Each Column: [4. 5. 6.]
(*): Standard Deviation of the Entire Array: 2.581988897471611
